// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC_VcZ63q9dfBChYAstDci30wrTyUIDs-Q',
    appId: '1:589670852064:web:55b30322a95ac3b2217785',
    messagingSenderId: '589670852064',
    projectId: 'loginpage-96bba',
    authDomain: 'loginpage-96bba.firebaseapp.com',
    storageBucket: 'loginpage-96bba.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDWBorhSOGbkBFJKvMzutsA_QSdG6--hqA',
    appId: '1:589670852064:android:80a3a45564044334217785',
    messagingSenderId: '589670852064',
    projectId: 'loginpage-96bba',
    storageBucket: 'loginpage-96bba.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDDcrdqND6cG8NUvF9vAX1NBYrTaj2aSbU',
    appId: '1:589670852064:ios:8eb46b44adc734cd217785',
    messagingSenderId: '589670852064',
    projectId: 'loginpage-96bba',
    storageBucket: 'loginpage-96bba.appspot.com',
    iosClientId: '589670852064-5a4bqahes5c8icah9ljmoktm45kmu8pm.apps.googleusercontent.com',
    iosBundleId: 'com.example.firstapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDDcrdqND6cG8NUvF9vAX1NBYrTaj2aSbU',
    appId: '1:589670852064:ios:8eb46b44adc734cd217785',
    messagingSenderId: '589670852064',
    projectId: 'loginpage-96bba',
    storageBucket: 'loginpage-96bba.appspot.com',
    iosClientId: '589670852064-5a4bqahes5c8icah9ljmoktm45kmu8pm.apps.googleusercontent.com',
    iosBundleId: 'com.example.firstapp',
  );
}
